# Generated by Django 6.0.5 on 2026-05-10 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_pegawai_nip'),
        ('rincian', '0002_remove_rincianbiaya_sppd_and_more'),
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(choices=[('tiket_pesawat', 'Tiket Pesawat'), ('boarding_pass', 'Boarding Pass'), ('tiket_travel', 'Tiket Travel'), ('tiket_kapal', 'Tiket Kapal'), ('hotel', 'Hotel'), ('bbm', 'BBM'), ('tol', 'Tol'), ('parkir', 'Parkir'), ('taxi', 'Taxi'), ('laporan', 'Laporan'), ('dokumentasi', 'Dokumentasi'), ('lainnya', 'Lainnya')], max_length=30)),
                ('file', models.FileField(upload_to='dokumen/')),
                ('nama_file', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rincian_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_list', to='rincian.rincianbiayaitem')),
                ('sppd_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_list', to='sppd.sppdpegawai')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiSakti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kwitansi', models.CharField(max_length=100)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='kwitansi_sakti/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwitansi_list', to='sppd.sppd')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pegawai')),
            ],
        ),
    ]
