# Generated by Django 6.0.5 on 2026-05-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincian', '0001_initial'),
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rincianbiaya',
            name='sppd',
        ),
        migrations.RemoveField(
            model_name='rincianbiayaitem',
            name='bukti',
        ),
        migrations.AddField(
            model_name='rincianbiaya',
            name='sppd_pegawai',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rincian_biaya', to='sppd.sppdpegawai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='jumlah_dokumen',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='wajib_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rincianbiayaitem',
            name='jenis_biaya',
            field=models.CharField(choices=[('transport', 'Transport'), ('penginapan', 'Penginapan'), ('uang_harian', 'Uang Harian'), ('representasi', 'Representasi'), ('tiket_pesawat', 'Tiket Pesawat'), ('tiket_travel', 'Tiket Travel'), ('tiket_kapal', 'Tiket Kapal'), ('bbm', 'BBM'), ('tol', 'Tol'), ('parkir', 'Parkir'), ('taxi', 'Taxi'), ('lainnya', 'Lainnya')], max_length=30),
        ),
    ]
