# Generated by Django 6.0.5 on 2026-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincian', '0002_remove_rincianbiaya_sppd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='jumlah_satuan',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rincianbiayaitem',
            name='satuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
