# Generated by Django 6.0.5 on 2026-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pegawai_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='nip',
        ),
    ]
