# Generated by Django 6.0.5 on 2026-05-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_pegawai_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat_tugas', models.CharField(max_length=100)),
                ('nomor_sppd', models.CharField(blank=True, max_length=100, null=True)),
                ('untuk', models.TextField()),
                ('tujuan', models.CharField(max_length=255)),
                ('alat_angkutan', models.CharField(max_length=100)),
                ('tanggal_berangkat', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('lama_perjalanan', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proses', 'Proses'), ('lengkap', 'Lengkap'), ('arsip', 'Arsip')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='SPPDDasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField()),
                ('isi', models.TextField()),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dasar_list', to='sppd.sppd')),
            ],
        ),
        migrations.CreateModel(
            name='SPPDMenimbang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField()),
                ('isi', models.TextField()),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menimbang_list', to='sppd.sppd')),
            ],
        ),
        migrations.CreateModel(
            name='SPPDPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kelengkapan', models.CharField(choices=[('belum', 'Belum Lengkap'), ('lengkap', 'Lengkap')], default='belum', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pegawai')),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_list', to='sppd.sppd')),
            ],
        ),
    ]
