# Generated by Django 6.0.5 on 2026-05-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pegawai_nip'),
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='penandatangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppd_penandatangan_set', to='accounts.pegawai'),
        ),
    ]
