# Generated by Django 6.0.5 on 2026-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd', '0002_sppd_penandatangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMenimbang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField(help_text='Urutan penampilan menimbang', unique=True)),
                ('isi', models.TextField(help_text="Isi menimbang. Gunakan {untuk} untuk placeholder field 'untuk' dari SPPD")),
                ('aktif', models.BooleanField(default=True, help_text='Jika aktif, akan ditampilkan di surat tugas baru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Default Menimbang',
                'ordering': ['urutan'],
            },
        ),
    ]
